-- INSERT INTO bootcamp (description)
-- VALUES

-- ("We're all lazy developers"),
-- ('You\'re not gonna need this'),
-- ('What does clean code mean to you?'),
-- ('Mark and Marc duo'),
-- ('Eli you\'re on mute'),
-- ('Let\'s get cracking'),
-- ('“So who wants to share their screen” *cue silence*'),
-- ('Johnny + his fun backgrounds'),
-- ('Cabral casually being an encyclopedia for specific facts'),
-- ('Carlee cat sighting'),
-- ('More than 10 people have their cameras off'),
-- ('Unstable internet'),
-- ('*Fiddles around trying to leave meeting*');